baseurl = "https://wisabd.github.io/"
title = "M. Wisal Abdullah"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"


[pagination]
pagerSize = 20

[services]
[services.disqus]
shortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[params]
  author = "M. Wisal Abdullah"
  info = "AI Engineering and Computational Physics"
  description = "Professional Portfolio website"
  keywords = "ai developer,professional, physics"
  avatarurl = "images/avatar.jpg"
  #gravatar = "john.doe@example.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2019

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/wisabd"
[[params.social]]
  name = "Gitlab"
  icon = "fa-brands fa-gitlab fa-2x"
  weight = 2
  url = "https://gitlab.com/johndoe/"
[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-x-twitter fa-2x"
  weight = 3
  url = "https://www.linkedin.com/in/m-wisal-abdullah-007a6464/"

# Menu links
[[menu.main]]
  name = "Summary"
  weight = 1
  url  = "summary/"

[[menu.main]]
  name = "Skills"
  weight = 2
  url  = "skills/"

[[menu.main]]
  name = "Opensource"
  weight = 3
  url  = "opensource/"

[[menu.main]]
  name = "Research"
  weight = 4
  url  = "research/"

[[menu.main]]
  name = "Education"
  weight = 5
  url  = "education/"

[[menu.main]]
  name = "Medium"
  weight = 6
  url  = "medium/"

[[menu.main]]
  name = "Academic Projects"
  weight = 7
  url  = "academic-projects/"

[[menu.main]]
  name = "Blog"
  weight = 8
  url  = "posts/"

[[menu.main]]
  name = "About"
  weight = 9
  url = "about/"

